# frozen_string_literal: true

# Seeds municipalities of Mexico (~2,469 municipios + 16 alcaldías CDMX).
# Run: rails runner db/seed_municipios.rb
# Skips municipalities that already exist per state.

MUNICIPIOS = {
  "AGS" => %w[Aguascalientes Asientos Calvillo Cosío Jesús_María Pabellón_de_Arteaga Rincón_de_Romos San_José_de_Gracia Tepezalá El_Llano San_Francisco_de_los_Romo],
  "BC" => %w[Ensenada Mexicali Tecate Tijuana Playas_de_Rosarito San_Quintín San_Felipe],
  "BCS" => %w[Comondú Mulegé La_Paz Los_Cabos Loreto],
  "CAM" => %w[Calkiní Campeche Carmen Champotón Hecelchakán Hopelchén Palizada Seybaplaya Tenabo Escárcega Calakmul Candelaria Dzitbalché],
  "COAH" => %w[Abasolo Acuña Allende Arteaga Candela Castaños Cuatro_Ciénegas Escobedo Francisco_I._Madero Frontera General_Cepeda Guerrero Hidalgo Jiménez Juárez Lamadrid Matamoros Monclova Morelos Múzquiz Nadadores Nava Ocampo Parras Piedras_Negras Progreso Ramos_Arizpe Sabinas Sacramento Saltillo San_Buenaventura San_Juan_de_Sabinas San_Pedro Sierra_Mojada Torreón Viesca Villa_Unión Zaragoza],
  "COL" => %w[Armería Colima Comala Coquimatlán Cuauhtémoc Ixtlahuacán Manzanillo Minatitlán Tecomán Villa_de_Álvarez],
  "CDMX" => %w[Álvaro_Obregón Azcapotzalco Benito_Juárez Coyoacán Cuajimalpa_de_Morelos Cuauhtémoc Gustavo_A._Madero Iztacalco Iztapalapa La_Magdalena_Contreras Miguel_Hidalgo Milpa_Alta Tláhuac Tlalpan Venustiano_Carranza Xochimilco],
  "CHIS" => %w[Acacoyagua Acala Acapetahua Aldama Altamirano Amatán Amatenango_de_la_Frontera Amatenango_del_Valle Angel_Albino_Corzo Arriaga Bejucal_de_Ocampo Bella_Vista Berriozábal Bochil El_Bosque Cacahoatán Catazajá Cintalapa Coapilla Comitán_de_Domínguez La_Concordia Copainalá Chalchihuitán Chamula Chanal Chapultenango Chenalhó Chiapa_de_Corzo Chiapilla Chicoasén Chicomuselo Chilón Escuintla Francisco_León Frontera_Comalapa Frontera_Hidalgo La_Grandeza Huehuetán Huixtán Huitiupán Huixtla La_Independencia Ixhuatán Ixtacomitán Ixtapa Ixtapangajoya Jiquipilas Jitotol Juárez Larráinzar La_Libertad Mapastepec Las_Margaritas Mazapa_de_Madero Mazatán Metapa Mitontic Motozintla Nicolás_Ruíz Ocosingo Ocotepec Ocozocoautla_de_Espinosa Ostuacán Osumacinta Oxchuc Palenque Pantelhó Pantepec Pichucalco Pijijiapan El_Porvenir Villa_Comaltitlán Pueblo_Nuevo_Solistahuacán Rayón Reforma Las_Rosas Sabanilla Salto_de_Agua San_Cristóbal_de_las_Casas San_Fernando Siltepec Simojovel Sitalá Socoltenango Solosuchiapa Soyaló Suchiapa Suchiate Sunuapa Tapachula Tapalapa Tapilula Tecpatán Tenejapa Teopisca Tila Tonalá Totolapa La_Trinitaria Tumbalá Tuxtla_Gutiérrez Tuxtla_Chico Tuzantán Tzimol Unión_Juárez Venustiano_Carranza Villa_Corzo Villaflores Yajalón San_Lucas Zinacantán San_Juan_Cancuc Benemérito_de_las_Américas Marqués_de_Comillas Montecristo_de_Guerrero San_Andrés_Duraznal Santiago_el_Pinar Emiliano_Zapata Mezcalapa Honduras_de_la_Sierra],
  "CHIH" => %w[Ahumada Aldama Allende Aquiles_Serdán Ascensión Bachíniva Balleza Batopilas Bocoyna Buenaventura Camargo Carichí Casas_Grandes Coronado Coyame La_Cruz Cuauhtémoc Cusihuiriachi Chihuahua Chínipas Delicias Dr_Belisario_Dominguez Galeana Santa_Isabel Gómez_Farías Gran_Morelos Guachochi Guadalupe Guadalupe_y_Calvo Guazapares Guerrero Hidalgo_del_Parral Huejotitán Ignacio_Zaragoza Janos Jiménez Juárez Julimes López Madera Maguarichi Manuel_Benavides Matachí Matamoros Meoqui Morelos Moris Namiquipa Nonoava Nuevo_Casas_Grandes Ocampo Ojinaga Praxedis_Guerrero Riva_Palacio Rosales Rosario San_Francisco_de_Borja San_Francisco_de_Conchos San_Francisco_del_Oro Santa_Bárbara Satevó Saucillo Temósachic El_Tule Urique Uruachi Valle_de_Zaragoza],
  "DGO" => %w[Canatlán Canelas Coneto_de_Comonfort Cuencamé Durango General_Simón_Bolívar Gómez_Palacio Guadalupe_Victoria Guanaceví Hidalgo Indé Lerdo Mapimí Mezquital Nazas Nombre_de_Dios Ocampo El_Oro Otáez Pánuco_de_Coronado Peñón_Blanco Poanas Pueblo_Nuevo Rodeo San_Bernardo San_Dimas San_Juan_de_Guadalupe San_Juan_del_Río San_Luis_del_Cordero San_Pedro_del_Gallo Santa_Clara Santiago_Papasquiaro Súchil Tamazula Tepehuanes Tlahualilo Topia Vicente_Guerrero Nuevo_Ideal],
  "GTO" => %w[Abasolo Acámbaro San_Miguel_de_Allende Apaseo_el_Alto Apaseo_el_Grande Atarjea Celaya Manuel_Doblado Comonfort Coroneo Cortazar Cuerámaro Doctor_Mora Dolores_Hidalgo Guanajuato Huanímaro Irapuato Jaral_del_Progreso Jerécuaro León Moroleón Ocampo Pénjamo Pueblo_Nuevo Purísima_del_Rincón Romita Salamanca Salvatierra San_Diego_de_la_Unión San_Felipe San_Francisco_del_Rincón San_José_Iturbide San_Luis_de_la_Paz Santa_Catarina Santa_Cruz_de_Juventino_Rosas Santiago_Maravatío Silao_de_la_Victoria Tarandacuao Tarimoro Tierra_Blanca Uriangato Valle_de_Santiago Victoria Villagrán Xichú Yuriria],
  "GRO" => %w[Acapulco_de_Juárez Ahuacuotzingo Ajuchitlán_del_Progreso Alcozauca Alpoyeca Apaxtla Arcelia Atenango_del_Río Atlamajalcingo Atlixtac Atoyac_de_Álvarez Ayutla Azoyú Benito_Juárez Buenavista_de_Cuéllar Coahuayutla Cocula Copala Copalillo Copanatoyac Coyuca_de_Benítez Coyuca_de_Catalán Cuajinicuilapa Cualác Cuautepec Cuetzala Cutzamala Chilapa_de_Álvarez Chilpancingo Florencio_Villarreal General_Canuto_Neri General_Heliodoro_Castillo Huamuxtitlán Huitzuco Iguala_de_la_Independencia Igualapa Ixcateopan Zihuatanejo Juan_R._Escudero Leonardo_Bravo Malinaltepec Mártir_de_Cuilapan Metlatónoc Mochitlán Olinalá Ometepec Pedro_Ascencio Alquisiras Petatlán Pilcaya Pungarabato Quechultenango San_Luis_Acatlán San_Marcos San_Miguel_Totolapan Taxco_de_Alarcón Tecoanapa Técpan Teloloapan Tepecoacuilco Tetipac Tixtla Tlacoachistlahuaca Tlacoapa Tlalchapa Tlalixtaquilla Tlapa Tlapehuala La_Unión_de_Isidoro_Montes Xalpatláhuac Xochihuehuetlán Xochistlahuaca Zapotitlán Zirándaro Zitlala Eduardo_Neri Acatepec Marquelia Cochoapa_el_Grande José_Joaquín_de_Herrera Juchitán Iliatenco],
  "HGO" => %w[Acatlán Acaxochitlán Actopan Agua_Blanca Ajacuba Alfajayucan Almoloya Apan El_Arenal Atitalaquia Atlapexco Atotonilco_el_Grande Atotonilco_de_Tula Calnali Cardonal Cuautepec Chapantongo Chapulhuacán Chilcuautla Eloxochitlán Emiliano_Zapata Epazoyucan Francisco_I._Madero Huasca Hueautla Huazalingo Huehuetla Huejutla Huichapan Ixmiquilpan Jacala Jaltocán Juárez_Hidalgo Lolotla Metepec Metzquititlán Metztitlán Mineral_del_Chico Mineral_del_Monte La_Misión Mixquiahuala Molango Nicolás_Flores Nopala Omitlán San_Felipe_Orizatlán Pacula Pachuca_de_Soto Pisaflores Progreso Mineral_de_la_Reforma San_Agustín_Tlaxiaca San_Bartolo_Tutotepec San_Salvador Santiago_de_Anaya Santiago_Tulantepec Singuilucan Tasquillo Tecozautla Tenango_de_Doria Tepeapulco Tepehuacán Tepeji Temamatla Temascalapa Temascalcingo Temascaltepec Temoaya Tenancingo Tenango_del_Aire Tenango_del_Valle Teoloyucan Teotihuacán Tepetlaoxtoc Tepetlixpa Tepotzotlán Tequixquiac Texcaltitlán Texcalyacac Texcoco Tezoyuca Tianguistenco Timilpan Tlalmanalco Tlalnepantla Tlatlaya Toluca Tonatico Tultepec Tultitlán Valle_de_Bravo Villa_de_Allende Villa_del_Carbón Villa_Guerrero Villa_Victoria Xonacatlán Zacazonapan Zacualpan Zinacantepec Zumpahuacán Zumpango Cuautitlán_Izcalli Valle_de_Chalco Luvianos San_José_del_Rincón Tonanitla],
  "JAL" => %w[Acatic Acatlán Ahualulco Amacueca Amatitán Ameca Arandas El_Arenal Atemajac Atengo Atenguillo Atotonilco_el_Alto Atoyac Autlán Ayotlán Ayutla La_Barca Bolaños Cabo_Corrientes Casimiro_Castillo Cihuatlán Zapotlán_el_Grande Cocula Colotlán Concepción_de_Buenos_Aires Cuautitlán Cuautla Cuquío Chapala Chimaltitán Chiquilistlán Degollado Ejutla Encarnación_de_Díaz Etzatlán El_Grullo Guachinango Guadalajara Hostotipaquillo Huejúcar Huejuquilla La_Huerta Ixtlahuacán_de_los_Membrillos Ixtlahuacán_del_Río Jalostotitlán Jamay Jesús_María Jilotlán Jocotepec Juanacatlán Juchitlán Lagos_de_Moreno El_Limón Magdalena Santa_María_del_Oro La_Manzanilla Mascota Mazamitla Mexticacán Mezquitic Mixtlán Ocotlán Ojuelos Pihuamo Poncitlán Puerto_Vallarta Villa_Purificación Quitupan El_Salto San_Cristóbal_de_la_Barranca San_Diego_de_Alejandría San_Juan_de_los_Lagos San_Julián San_Marcos San_Martín_de_Bolaños San_Martín_Hidalgo San_Miguel_el_Alto Gómez_Farías San_Sebastián_del_Oeste Santa_María_de_los_Ángeles Sayula Tala Talpa Tamazula Tapalpa Tecalitlán Tecolotlán Techaluta Tenamaxtlán Teocaltiche Teocuitatlán Tepatitlán Tequila Teuchitlán Tizapán Tlajomulco San_Pedro_Tlaquepaque Tolimán Tomatlán Tonalá Tonaya Tonila Totatiche Tototlán Tuxcacuesco Tuxcueca Tuxpan Unión_de_San_Antonio Unión_de_Tula Valle_de_Guadalupe Valle_de_Juárez San_Gabriel Villa_Corona Villa_Guerrero Villa_Hidalgo Cañadas_de_Obregón Yahualica Zacoalco Zapopan Zapotiltic Zapotitlán Zapotlán_del_Rey Zapotlanejo San_Ignacio_Cerro_Gordo],
  "MEX" => %w[Acambay Acolman Aculco Almoloya_de_Alquisiras Almoloya_de_Juárez Almoloya_del_Río Amanalco Amatepec Amecameca Apaxco Atenco Atizapán Atizapán_de_Zaragoza Atlacomulco Atlautla Axapusco Ayapango Calimaya Capulhuac Coacalco Coatepec_Harinas Cocotitlán Coyotepec Cuautitlán Chalco Chapa_de_Mota Chapultepec Chiautla Chicoloapan Chiconcuac Chimalhuacán Donato_Guerra Ecatepec Ecatzingo Huehuetoca Hueypoxtla Huixquilucan Isidro_Fabela Ixtapaluca Ixtapan_de_la_Sal Ixtapan_del_Oro Ixtlahuaca Xalatlaco Jaltenco Jilotepec Jilotzingo Jiquipilco Jocotitlán Joquicingo Juchitepec Lerma Malinalco Melchor_Ocampo Metepec Mexicaltzingo Morelos Naucalpan Nezahualcóyotl Nextlalpan Nicolás_Romero Nopaltepec Ocoyoacac Ocuilan El_Oro Otumba Otzoloapan Otzolotepec Ozumba Papalotla La_Paz Polotitlán Rayón San_Antonio_la_Isla San_Felipe_del_Progreso San_Martín_de_las_Pirámides San_Mateo_Atenco San_Simón_de_Guerrero Santo_Tomás Soyaniquilpan Sultepec Tecámac Tejupilco Temamatla Temascalapa Temascalcingo Temascaltepec Temoaya Tenancingo Tenango_del_Aire Tenango_del_Valle Teoloyucan Teotihuacán Tepetlaoxtoc Tepetlixpa Tepotzotlán Tequixquiac Texcaltitlán Texcalyacac Texcoco Tezoyuca Tianguistenco Timilpan Tlalmanalco Tlalnepantla Tlatlaya Toluca Tonatico Tultepec Tultitlán Valle_de_Bravo Villa_de_Allende Villa_del_Carbón Villa_Guerrero Villa_Victoria Xonacatlán Zacazonapan Zacualpan Zinacantepec Zumpahuacán Zumpango Cuautitlán_Izcalli Valle_de_Chalco Luvianos San_José_del_Rincón Tonanitla],
  "MICH" => %w[Acuitzio Aguililla Álvaro_Obregón Angamacutiro Angangueo Apatzingán Aporo Aquila Ario Arteaga Briseñas Buenavista Carácuaro Coahuayana Coalcomán Coeneo Contepec Copándaro Cotija Cuitzeo Charapan Charo Chavinda Cherán Chilchota Chinicuila Chucándiro Churintzio Churumuco Ecuandureo Epitacio_Huerta Erongarícuaro Gabriel_Zamora Hidalgo La_Huacana Huandacareo Huaniqueo Huetamo Huiramba Indaparapeo Irimbo Ixtlán Jacona Jiménez Jiquilpan Juárez Jungapeo Lagunillas Madero Maravatío Marcos_Castellanos Lázaro_Cárdenas Morelia Morelos Múgica Nahuatzen Nocupétaro Nuevo_Parangaricutiro Nuevo_Urecho Numarán Ocampo Pajacuarán Panindícuaro Paracho Parácuaro Pátzcuaro Penjamillo Peribán La_Piedad Purépero Puruándiro Queréndaro Quiroga Los_Reyes Sahuayo San_Lucas Santa_Ana_Maya Salvador_Escalante Senguio Susupuato Tacámbaro Tancítaro Tangamandapio Tangancícuaro Tanhuato Taretan Tarímbaro Tepalcatepec Tingambato Tingüindín Tiquicheo Tlalpujahua Tlazazalca Tocumbo Tumbiscatío Turicato Tuxpan Tuzantla Tzintzuntzan Tzitzio Uruapan Venustiano_Carranza Villamar Vista_Hermosa Yurécuaro Zacapu Zamora Zináparo Zinapécuaro Ziracuaretiro Zitácuaro José_Sixto_Verduzco],
  "MOR" => %w[Amacuzac Atlatlahucan Axochiapan Ayala Coatlán_del_Río Cuautla Cuernavaca Emiliano_Zapata Huitzilac Jantetelco Jiutepec Jojutla Jonacatepec Mazatepec Miacatlán Ocuituco Puente_de_Ixtla Temixco Tepalcingo Tepoztlán Tetecala Tetela_del_Volcán Tlalnepantla Tlaltizapán Tlaquiltenango Tlayacapan Totolapan Xochitepec Yautepec Yecapixtla Zacatepec Zacualpan Temoac Coatetelco],
  "NAY" => %w[Acaponeta Ahuacatlán Amatlán_de_Cañas Compostela Huajicori Ixtlán_del_Río Jala Xalisco Del_Nayar Rosamorada Ruíz San_Blas San_Pedro_Lagunillas Santa_María_del_Oro Santiago_Ixcuintla Tecuala Tepic Tuxpan La_Yesca Bahía_de_Banderas],
  "NL" => [], # Already seeded
  "OAX" => %w[Abejones Acatlán Asunción_Cacalotepec Asunción_Cuyotepeji Asunción_Ixtaltepec Asunción_Nochixtlán Asunción_Ocotlán Asunción_Tlacolulita Ayotzintepec El_Barrio_de_la_Soledad Calihualá Candelaria_Loxicha Ciénega_de_Zimatlán Ciudad_Ixtepec Coatecas_Altas Coicoyán_de_las_Flores La_Compañía Concepción_Buenavista Concepción_Pápalo Constancia_del_Rosario Cosolapa Cosoltepec Cuilápam Cuyamecalco Chahuites Chalcatongo Chiquihuitlán Ejutla El_Espinal Eloxochitlán Fresnillo_de_Trujano Guadalupe_Etla Guadalupe_de_Ramírez Guelatao Guevea Huasca Hueautla Huazalingo Huehuetla Huejutla Huichapan Ixmiquilpan Jacala Jaltocán Juárez_Hidalgo Lolotla Metepec Metzquititlán Metztitlán Mineral_del_Chico Mineral_del_Monte La_Misión Mixquiahuala Molango Nicolás_Flores Nopala Omitlán San_Felipe_Orizatlán Pacula Pachuca Pisaflores Progreso Mineral_de_la_Reforma San_Agustín_Tlaxiaca San_Bartolo_Tutotepec San_Salvador Santiago_de_Anaya Santiago_Tulantepec Singuilucan Tasquillo Tecozautla Tenango_de_Doria Tepeapulco Tepehuacán Tepeji Tepetitlán Tetepango Villa_de_Tezontepec Tezontepec Tianguistengo Tizayuca Tlahuelilpan Tlahuiltepa Tlanalapa Tlanchinol Tlaxcoapan Tolcayuca Tula Tulancingo Xochiatipan Xochicoatlán Yahualica Zacualtipán Zapotlán Zempoala Zimapán],
  "PUE" => %w[Acajete Acateno Acatzingo Acteopan Ahuacatlán Ahuatlán Ahuazotepec Ahuehuetitla Ajalpan Albino_Zertuche Aljojuca Altepexi Amixtlán Amozoc Aquixtla Atempan Atexcal Atoyatempan Atzala Atzitzihuacán Atzitzintla Axutla Ayotoxco Calpan Caltepec Camocuautla Caxhuacan Coatepec Coatzingo Cohetzala Cohuecan Coronango Coxcatlán Coyomeapan Coyotepec Cuapiaxtla Cuautempan Cuautinchán Cuautlancingo Cuayuca_de_Andrade Cuetzalan_Cuyoaco Chalchicomula_de_Sesma Chapulco Chiautla Chiautzingo Chiconcuautla Chichiquila Chietla Chigmecatitlán Chignahuapan Chignautla Chila Chila_de_la_Sal Chilchotla Chinantla Domingo_Arenas Eloxochitlán Epatlán Esperanza Francisco_Z._Mena General_Felipe_Ángeles Guadalupe Guerrero Huaquechula Huehuetla Huejotzingo Hueyapan Hueytamalco Hueytlalpan Huitzilan Huitziltepec Ixcamilpa Ixcaquixtla Ixtacamaxtitlán Ixtepec Izúcar_de_Matamoros Jalpan Juan_Galindo Juan_N._Méndez Lafragua Libres_Resurrección Los_Reyes_de_Juárez Magdalena_Tlatlauquitepec Mazapiltepec_de_Juárez Mixtla Molcaxac Naupan Nauzontla Nealtican Nicolás_Bravo Nopalucan Ocotepec Ocoyucan Olintla Oriental Pahuatlán Palmar_de_Bravo Pantepec Petlalcingo Piaxtla Puebla Quecholac Quimixtlán Rafael_Lara_Grajales San_Andrés_Cholula San_Antonio_Cañada San_Diego_la_Mesa San_Felipe_Teotlalcingo San_Gabriel_Tlaixpa San_Gregorio_Atzompa San_Jerónimo_Tecuanipan San_José_Chiapa San_José_Miahuatlán San_Juan_Atzompa San_Martín_Texmelucan San_Matías_Tlalancaleca San_Miguel_Ixitlán San_Miguel_Xoxtla San_Nicolás_Buenos_Aires San_Nicolás_de_los_Ranchos San_Pablo_Anicano San_Pedro_Cholula San_Pedro_Yeloixtlahuaca San_Salvador_el_Seco San_Salvador_el_Verde San_Salvador_Huixcolotla Santa_María_del_Monte Santa_Inés_Ahuatempan Santa_Isabella_Xiloxoxtla Santiago_Miahuatlán Santo_Tomás_Hueyotlipan Soltepec Tecali_de_Herrera Tecamachalco Tecomatlán Tehuacán Tehuitzingo Tenampulco Tepanco_de_López Tepango_de_Rodríguez Tepatlaxco_de_Hidalgo Tepeaca Tepemaxalco Tepeojuma Tepetzintla Tepexco Tepexi_de_Rodríguez Tepeyahualco Tepeyahualco_de_Cuauhtémoc Tetela_de_Ocampo Teteles_de_Ávila_Castillo Teziutlán Tianguismanalco Tilapa Tlacotepec Tlacuilotepec Tlachichuca Tlacuilotepec Tlahuapan Tlaltenango Tlanepantla Tlaola Tlapacoya Tlapanalá Tlatlauquitepec Tlaxco Tochtepec Totutla Xayacatlán_de_Bravo Xicotepec Xicotlán Xiutetelco Xochiapulco Xochiltepec Xochitlán_de_Vicente_Suárez Xochitlán_Todos_Santos Yaonáhuac Yehualtepec Zacapala Zacapoaxtla Zacatlán Zapotitlán Zapotitlán_de_Méndez Zaragoza Zautla Zoquiapán Zoquitlán],
  "QRO" => %w[Amealco_de_Bonfil Arroyo_Seco Cadereyta_de_Montes Colon Ezequiel_Montes Huimilpan Jalpan_de_Serra Landa_de_Matamoros El_Marqués Pedro_Escobedo Peñamiller Pinal_de_Amoles Querétaro San_Joaquín San_Juan_del_Río Tequisquiapan Tolimán],
  "QROO" => %w[Bacalar Benito_Juárez Cozumel Felipe_Carrillo_Puerto Isla_Mujeres José_María_Morelos Lázaro_Cárdenas Othón_P._Blanco Solidaridad Tulum],
  "SLP" => %w[Ahualulco Aquismón Armadillo_de_los_Infante Cárdenas Catorce Cedral Cerritos Cerrito_de_Santiago Charcas Ciudad_del_Maíz Ciudad_Fernández Ciudad_Valles Coxcatlán Ebano Guadalcázar Huehuetlán Lagunillas Matehuala Mexquitic_de_Carmona Moctezuma Rayón Rioverde Salinas San_Antonio San_Ciro_de_Acosta San_Luis_Potosí San_Martín_Chalchicuautla San_Nicolás_Tolentino Santa_Catarina Santa_María_del_Río Santo_Domingo Tamazunchale Tampacán Tampamolón_Coronas Tamuín Tanlajás Tanquián_de_Escobedo Tierra_Nueva Vanegas Venado Villa_de_Arriaga Villa_de_Guadalupe Villa_de_la_Paz Villa_de_Ramos Villa_de_Reyes Villa_Hidalgo Villa_Juárez Xilitla Zaragoza],
  "SIN" => %w[Ahome Angostura Badiraguato Choix Concordia Cosalá Culiacán El_Fuerte Escuinapa Guasave Mazatlán Mocorito Naguaato Navolato Rosario Salvador_Alvarado San_Ignacio Sinaloa],
  "SON" => %w[Aconchi Agua_Prieta Alamos Altar Arivechi Arizpe Atil Bacadéhuachi Bachoco Bácum Banámichi Bavispe Benjamín_Hill Caborca Cajeme Cananea Carbó Cucurpe Cumpas Divisaderos Empalme Fronteras Granados Guaymas Hermosillo Huachinera Huásabas Huatabampo Imuris La_Colorada Magdalena Mazatán Moctezuma Naco Nácori_Chico Nacozari_de_García Navojoa Nogales Onavas Opodepe Oquitoa Pitiquito Puerto_Peñasco Quiriego Rayón Rosario Sahuaripa San_Felipe San_Javier San_Miguel_de_Horcasitas San_Pedro_de_la_Cueva Santa_Ana Santa_Cruz Sáric Soyopa Suaqui_Grande Tepache Trincheras Tubutama Ures Villa_Pesqueira Yécora],
  "TAB" => %w[Balancán Cárdenas Centla Comalcalco Cunduacán Emiliano_Zapata Huimanguillo Jalapa Jalpa_de_Méndez Jonuta Macuspana Nacajuca Paraíso Tacotalpa Teapa Tenosique Villahermosa],
  "TAM" => %w[Abasolo Aldama Altamira Antiguo_Morelos Burgos Bustamante Camargo Casas Ciudad_Madero Cruillas Gómez_Farías González Güémez Guerrero Gustavo_Díaz_Ordaz Hidalgo Jaumave Jiménez Llera Mainero El_Mante Matamoros Méndez Mier Miguel_Alemán Miquihuana Nuevo_Laredo Nuevo_Morelos Ocampo Padilla Palmillas Reynosa Río_Bravo San_Carlos San_Fernando San_Nicolás Soto_la_Marina Tampico Tula Valle_Hermoso Victoria Villagrán Xicoténcatl],
  "TLAX" => %w[Amaxac_de_Guerrero Apizaco Atlangatepec Atlzayanca Benito_Juárez Calpulalpan Cuapiaxtla Cuaxomulco Chiautempan Contla_de_Juan_Cuamatzi Huamantla Hueyotlipan Ixtacuixtla Ixtenco Mazatecochco_de_José_María_Morelos Contla Tetla_de_Tlatelolco Tlaxcala Tlaxcoapan Tocatlán Totolac Tultitlán_de_Guadalupe Tzompantepec Xalostoc Xaltocan Papalotla_de_Xicohténcatl Xicohtzinco Yauhquemehcan Zacatelco San_Damián_Texóloc San_Francisco_Tetlanohcan San_Jerónimo_Zacualpan San_José_Teacalco San_Juan_Huactzinco San_Lorenzo_Axocomanitla San_Lucas_Tecopilco Santa_Ana_Nopalucan Santa_Apolonia_Teacalco Santa_Catarina_Ayometla Santa_Cruz_Quilehtla Santa_Isabel_Xiloxoxtla],
  "VER" => %w[Acajete Acatlán Acayucan Actopan Acula Acultzingo Camarón_de_Tejeda Alpatláhuac Alto_Lucero Altotonga Alvarado Amatlán_de_los_Reyes Amatitlán Apazapan Aquila Astacinga Atlahuilco Atoyac Atzacan Atzalán Ayahualulco Banderilla Benito_Juárez Boca_del_Río Calcahualco Camerino_Z._Mendoza Carrillo_Puerto Castillo_de_Teayo Catemaco Cazones Coatepec Coatzacoalcos Coatzintla Coetzala Colipa Comapa Córdoba Cosamaloapan Cosautlán_de_Carvajal Coscomatepec Cosoleacaque Cotaxtla Coxquihui Coyutla Cuichapa Cuitláhuac Chacaltianguis Chalma Chiconamel Chiconquiaco Chicontepec Chinameca Chinampa_de_Gorostiza Chocamán Chontla Chumatlán Citlaltépetl Coacoatzintla Coahuitlán Coetzala Comapa Cosamaloapan Cosautlán Coscomatepec Cosoleacaque Cotaxtla Coxquihui Coyutla Cuichapa Cuitláhuac Emiliano_Zapata Espinal Filomeno_Mata Fortín Gutiérrez_Zamora Hidalgotitlán Huatusco Huayacocotla Hueyapan_de_Ocampo Huiloapan Ilamatlán Isla Ixcatepec Ixhuacán Ixhuatlán_del_Café Ixhuatlán_de_Madero Ixhuatlán_del_Sureste Ixhuatlancillo Ixmatlahuacan Ixtaczoquitlán Jalacingo Jalcomulco Jáltipan Jamapa Jesús_Carranza Jilotepec José_Azueta Juan_Rodríguez_Clara Juchique_de_Ferrer Landero_y_Coss Las_Choapas Las_Minas Las_Vigas Lerdo_de_Tejada Los_Reyes Magdalena Maltrata Manuel_Doblado Mariano_Escobedo Martínez_de_la_Torre Mecatlán Mecayapan Medina_Magdalena Miahuatlán Minatitlán Mislanta Mixtla_de_Altamirano Moloacán Naolinco Naranjal Naranjos Nautla Nogales Oluta Omealca Orizaba Otatitlán Oteapan Ozuluama Pajapan Papantla Paso_del_Macho Paso_de_Ovejas Perote Platón_Sánchez Platón_Sánchez Playa_Vicente Poza_Rica Pueblo_Viejo Puente_Nacional Rafael_Delgado Rafael_Lucio Río_Blanco Saltabarranca San_Andrés_Tenejapan San_Andrés_Tuxtla San_Antonio_la_Isla San_Cristóbal San_Juan_Evangelista San_Rafael San_Andrés_Tuxtla Santiago_Socheapan Santiago_Tuxtla Sayula_de_Alemán Sochiapa Soconusco Soledad_Atzompa Soledad_de_Doblado Soteapan Tamalín Tamiahua Tampico_Alto Tancoco Tantima Tantoyuca Tatahuicapan_de_Juárez Tatatila Tecolutla Tehuipango Temapache Tempoal Tenampa Tenochtitlán Teocelo Tepatlaxco Tepehua Tepegua Tequila Texcatepec Texhuacán Texistepec Tezonapa Tierra_Blanca Tihuatlán Tlachichilco Tlacojalpan Tlacolulan Tlacotalpan Tlacotepec_de_Mejía Tlalixcoyan Tlalnelhuayocan Tlaltetela Tlapacoyan Tlaquilpa Tlilapan Tomatlán Tonayán Totutla Tuxpan Tuxtilla Uxpanapa Vega_de_Alatorre Vega_de_Alatorre Veracruz Villa_Aldama Xalapa Xico Yecuatla Zacualpan Zaragoza Zongolica Zontecomatlán],
  "YUC" => %w[Abalá Acanceh Akil Baca Bokobá Buctzotz Cacalchén Calotmul Cansahcab Cantamayec Celestún Cenotillo Conkal Cuncunul Cuzamá Chacsinkín Chankom Chapab Chenax Chichimilá Chikindzonot Chilón Chocholá Chumayel Dzan Dzemul Dzidzantún Dzilam_de_Bravo Dzilam_González Dzitás Dzoncauich Espita Halachó Hocabá Homún Huhí Hunucmá Ixil Izamal Kanasín Kantunil Kaua Kinchil Kopomá Mama Maní Maxcanú Mayapán Mérida Mocochá Motul Muna Muxupip Opichén Oxkutzcab Panabá Peto Progreso Quintana_Roo Río_Lagartos Sacalum Samahil San_Felipe Sanahcat Sotuta Sucilá Sudzal Suma Tahdziú Tahmek Teab Teabo Tecoh Tekal de Venegas Tekantó Tekax Tekit Tekom Telchac_Pueblo Telchac_Puerto Temax Temozón Tepakán Tetiz Teya Ticul Timucuy Tinum Tixcacalcupul Tixkokob Tixmehuac Tixpéhual Tizimín Tunkás Tzucacab Uayma Ucú Umán Valladolid Xocchel Yaxcabá Yaxkukul Yobaín],
  "ZAC" => %w[Apozol Apulco Atolinga Benito_Juárez Calera Cañitas_de_Felipe_Pescador Concepción_del_Oro Cuauhtémoc Chalchihuites Fresnillo Genaro_Codina General_Enrique_Estrada General_Francisco_R._Murguía Guadalupe Huanusco Jalpa Jerez Jiménez_del_Teúl Juan_Aldama Juchipila Loreto Luis_Moya Mazapil Melchor_Ocampo Mezquital_del_Oro Miguel_Auza Momax Monte_Escobedo Morelos Moyahua_de_Estrada Nochistlán Noria_de_Ángeles Ojocaliente Pánuco Pinos Puerto_Peñasco Río_Grande Sain_Alto Santa_María_de_la_Paz Sombrerete Susticacán Tabasco Tepechitlán Tepetongo Teúl_de_González_Ortega Tlaltenango_de_Sánchez_Román Trancoso Trinidad_García_de_la_Cadena Valparaíso Vetagrande Villa_de_Cos Villa_García Villa_González_Ortega Villa_Hidalgo Villanueva Zacatecas]
}

def normalize(name)
  name.to_s.tr("_", " ").split.map(&:capitalize).join(" ")
end

puts "=== Seeding municipalities of Mexico ==="

total_created = 0
total_skipped = 0

MUNICIPIOS.each do |code, names|
  next if names.empty?

  state = State.find_by!(code: code)
  created = 0
  skipped = 0

  names.each do |raw_name|
    name = normalize(raw_name)
    if Alcaldia.exists?(name: name, state_id: state.id)
      skipped += 1
    else
      Alcaldia.create!(name: name, state_id: state.id)
      created += 1
    end
  end

  total_created += created
  total_skipped += skipped
  puts "  #{state.name} (#{code}): +#{created} created, #{skipped} skipped (total: #{names.size})"
end

puts "\nTotal created: #{total_created}"
puts "Total skipped: #{total_skipped}"
puts "Total alcaldias in DB: #{Alcaldia.count}"
puts "=== Done ==="
